name: garden
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  auto_route: ^2.3.0
  dartz: ^0.10.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  injectable: ^1.5.0
  provider: ^6.0.0
  floor: ^1.1.0
  bloc_test: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.14.5
  injectable_generator: ^1.5.1
  auto_route_generator: ^2.3.0

flutter:

  uses-material-design: true

