name: garden
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  flutter_bloc: ^7.2.0
  dartz: ^0.10.0
  freezed_annotation: ^0.14.0
  get_it: ^7.0.0
  injectable: ^1.5.0
  provider: ^6.0.0
  floor: ^1.1.0
  bloc_test: ^8.1.0
  easy_localization: ^3.0.0
  built_collection: ^5.1.1
  another_flushbar: ^1.10.24
  flutter_hooks: ^0.18.0
  uuid: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.14.0
  injectable_generator: ^1.2.0
  auto_route_generator: ^2.0.0
  floor_generator: ^1.1.0
  lint: ^1.6.0

flutter:
  assets:
    - assets/translations/
  uses-material-design: true

